# lightning.pytorch==2.1.3
fit:
  seed_everything: 300495
  trainer:
    accelerator: auto
    strategy: auto
    devices: auto
    num_nodes: 1
    precision: null
    logger:
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /opt/ml/model/logs
        name: null
        version: convnet-1.1.1
        log_graph: false
        default_hp_metric: true
        prefix: ''
        sub_dir: null
    callbacks:
      - class_path: lightning.pytorch.callbacks.ModelCheckpoint
        init_args:
          dirpath: null
          filename: "{epoch}-{train_loss:.3f}-{val_mos_ovr:.3f}"
          monitor: train_loss
          verbose: false
          save_last: true
          save_top_k: 10
          save_weights_only: false
          mode: min
          auto_insert_metric_name: true
          every_n_train_steps: null
          train_time_interval: null
          every_n_epochs: 1
          save_on_train_epoch_end: null
          enable_version_counter: true
      - class_path: lightning.pytorch.callbacks.LearningRateMonitor
        init_args:
          logging_interval: "epoch"
          log_momentum: false
    fast_dev_run: false
    max_epochs: 10000
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: null
    limit_val_batches: null
    limit_test_batches: null
    limit_predict_batches: null
    overfit_batches: 0.0
    val_check_interval: null
    check_val_every_n_epoch: 1
    num_sanity_val_steps: null
    log_every_n_steps: null
    enable_checkpointing: null
    enable_progress_bar: null
    enable_model_summary: null
    accumulate_grad_batches: 4
    gradient_clip_val: null
    gradient_clip_algorithm: null
    deterministic: null
    benchmark: null
    inference_mode: true
    use_distributed_sampler: true
    profiler: null
    detect_anomaly: false
    barebones: false
    plugins: null
    sync_batchnorm: false
    reload_dataloaders_every_n_epochs: 0
    default_root_dir: null
  model:
    base_n_filters: 16
    bias: true
    n_fft: 512
    win_length: 512
    hop_length: 128
    p835_model_path: /opt/ml/input/data/mos/p835.onnx
    p808_model_path: /opt/ml/input/data/mos/p808.onnx
    global_stats_path: /opt/ml/input/data/mos/scaler.npy
  data:
    data_dir: /opt/ml/input/data
    sampling_rate: 16000
    num_workers: 4
    batch_size: 128
  optimizer:
    lr: 1e-3
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false
    maximize: false
    foreach: null
    capturable: false
    differentiable: false
    fused: null
# lr_scheduler:
#   monitor: val_mos_ovr
#   mode: max
#   factor: 0.5
#   patience: 10
#   threshold: 1e-4
#   threshold_mode: rel
#   cooldown: 0
#   min_lr: 1e-6
#   eps: 1.0e-08
#   verbose: false
